[tool.poetry]
name = "hitron-exporter"
version = "0.1.0"
description = ""
authors = ["Sam Morris <sam@robots.org.uk>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.0"
Flask = "^2.1.2"
prometheus-client = "^0.14.1"
gunicorn = {version = "^20.1.0", optional = true}
setproctitle = {version = "^1.2.3", optional = true}
# ipalib is broken by <https://jasonralph.org/?p=997>
cryptography = "<38"
# required by ipalib, but we need to specify here in order to enable the ldap extra
ipapython = {version = "^4.8.9", optional = true, extras = ["ldap"]}
ipaclient = {version = "^4.8.9", optional = true}

[tool.poetry.group.dev.dependencies]
httpie = "^3.2.1"
mypy = "^1.0.1"
types-requests = "^2.28.11.13"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# This bit is maintained by hand
[tool.poetry.extras]
freeipa-vault = ["ipaclient", "ipapython"]
container = ["gunicorn", "setproctitle"]

[tool.flake8]
# Recommend matching the black line length (default 88),
# rather than using the flake8 default of 79:
max-line-length = 88
extend-ignore = [
    # See https://github.com/PyCQA/pycodestyle/issues/373
    "E203",
]

[tool.mypy]
strict = true
