[tool.poetry]
name = "hitron-exporter"
version = "0.1.0"
description = ""
authors = ["Sam Morris <sam@robots.org.uk>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.0"
Flask = "^2.1.2"
prometheus-client = "^0.14.1"
python-ldap = {version = "^3.4.0", optional = true}
ipaclient = {version = "^4.8.9", optional = true}
gunicorn = {version = "^20.1.0", optional = true}
setproctitle = {version = "^1.2.3", optional = true}

[tool.poetry.dev-dependencies]
black = "^22.3.0"
httpie = "^3.2.1"
safety = "^2.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# This bit is maintained by hand
[tool.poetry.extras]
freeipa-vault = ["ipaclient", "python-ldap"]
container = ["gunicorn", "setproctitle"]
