name: Scan container image

on:
  schedule:
  - cron: 18 13 26 * *
    
jobs:

  scan:
    runs-on: ubuntu-latest

    steps:

    #- run: docker pull ghcr.io/yrro/hitron-exporter:latest

    - uses: azure/container-scan@v0
      with:
        image-name: ghcr.io/yrro/hitron-exporter:latest
