name: Build & publish container image

on:

  pull_request:

  push:
    branches:
    - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Record build timestamp
      run: echo date_rfc_5322=$(date -R) >> $GITHUB_ENV
      shell: bash

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ghcr.io/yrro/hitron-exporter
        containerfiles: |
          ./Containerfile
        labels: |
          org.opencontainers.image.created=${{ env.date_rfc_5322 }}
          org.opencontainers.image.source=${{ github.repositoryUrl }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.url=https://github.com/${{ github.repository }}

    - name: Extract base image from image
      run: echo image_base_ref=$(buildah inspect --type=image ghcr.io/yrro/hitron-exporter | jq '[.History[] | select((.comment // "") | startswith("FROM "))] | first | .comment[5:]' -r) >> $GITHUB_ENV
      shell: bash

    - name: Extract digest from base image
      run: echo image_base_digest=$(buildah inspect --type=image $image_base_ref | jq '.FromImageDigest' -r) >> $GITHUB_ENV
      shell: bash

    - name: Apply base image labels
      run: |
        buildah from --pull=false --name=w ghcr.io/yrro/hitron-exporter \
        && buildah config \
          --label org.opencontainers.image.base.name="$image_base_ref" \
          --label org.opencontainers.image.base.digest="$image_base_digest"\
          w \
        && buildah commit w ghcr.io/yrro/hitron-exporter
      shell: bash

    - name: Push image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ghcr.io/yrro/hitron-exporter
        registry: ghcr.io
        username: _ignored_
        password: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
