name: Build & publish container image

on:

  push:
    branches:
    - master

  workflow_dispatch: {}
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Build image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ghcr.io/yrro/hitron-exporter
        containerfiles: |
          ./Containerfile
        
    - name: Push image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ghcr.io/yrro/hitron-exporter
        registry: ghcr.io
        username: _ignored_
        password: ${{ secrets.GITHUB_TOKEN }}
