name: Build & publish container image

on:

  pull_request:

  push:

jobs:

  main:
    runs-on: ubuntu-latest
    steps:

    - name: Record build timestamp
      id: rfc_5322
      run: echo date=$(date -R) >> $GITHUB_OUTPUT
      shell: bash

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Construct PEP 440 version identifier
      id: pep_440
      run: echo version=$(git describe --match='version-marker' | sed s/version-marker-/0.1.0.dev/ | sed 's/-g/+git./') >> $GITHUB_OUTPUT
      shell: bash

    - name: Bump version number
      run: sed -i -e '0,/"0\.1\.0"/ { s//"${{ steps.pep_440.outputs.version }}"/ }' pyproject.toml
      shell: bash

    - name: Build image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ghcr.io/yrro/hitron-exporter
        containerfiles: Containerfile
        build-args: |
          nproc: 2
        labels: |
          org.opencontainers.image.created=${{ steps.rfc_5322.outputs.date }}
          org.opencontainers.image.source=${{ github.repositoryUrl }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.url=https://github.com/${{ github.repository }}

    - name: Extract base image from image
      id: image_base_ref
      run: echo ref=$(buildah inspect --type=image ghcr.io/yrro/hitron-exporter | jq '[.History[] | select((.comment // "") | startswith("FROM "))] | first | .comment[5:]' -r) >> $GITHUB_OUTPUT
      shell: bash

    - name: Extract digest from base image
      id: image_base_digest
      run: echo digest=$(buildah inspect --type=image ${{ steps.image_base_ref.outputs.ref }} | jq '.FromImageDigest' -r) >> $GITHUB_OUTPUT
      shell: bash

    - name: Create working container
      run: buildah from --pull=false --name=w ghcr.io/yrro/hitron-exporter
      shell: bash

    - name: Apply base image labels
      run: |
        buildah config \
          --label org.opencontainers.image.base.name=${{ steps.image_base_ref.outputs.ref }} \
          --label org.opencontainers.image.base.digest=${{ steps.image_base_digest.outputs.digest }} \
          w
      shell: bash

    - name: Commit working container
      run: buildah commit w ghcr.io/yrro/hitron-exporter
      shell: bash

    - name: Push image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ghcr.io/yrro/hitron-exporter
        registry: ghcr.io
        username: _ignored_
        password: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'push' && github.ref == 'refs/heads/master' # NOT a security check!
