name: Build & publish container image

on:

  push:
    branches:
    - master

  workflow_dispatch: {}
    
jobs:

  s2i:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Build image
      uses: redhat-actions/s2i-build@v2
      with:
        builder_image: 'registry.access.redhat.com/ubi9/python-39:latest'
        image: ghcr.io/yrro/hitron-exporter
        
    - name: Push image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ghcr.io/yrro/hitron-exporter
        registry: ghcr.io
        username: _ignored_
        password: ${{ secrets.GITHUB_TOKEN }}
