name: Scan container image

on:

  schedule:
  - cron: 18 13 26 * *
  
  workflow_dispatch: {}
    
jobs:

  scan:
    runs-on: ubuntu-latest

    steps:

    - uses: azure/container-scan@v0
      with:
        image-name: ghcr.io/yrro/hitron-exporter:latest
        format: sarif
        output: trivy-results.sarif

    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: trivy-results.sarif

